# Generated by Django 4.2.5 on 2023-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='studentparent',
            options={'verbose_name': 'Родитель ученика', 'verbose_name_plural': 'Родители учеников'},
        ),
        migrations.AlterModelOptions(
            name='studenttask',
            options={'verbose_name': 'Задание ученика', 'verbose_name_plural': 'Задания учеников'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Предмет учителя', 'verbose_name_plural': 'Предметы учителей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'Тип пользователя', 'verbose_name_plural': 'Типы пользователей'},
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
    ]
