# Generated by Django 4.2.5 on 2023-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_user_user_school_code_task_teacher_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ'),
        ),
    ]
