# Generated by Django 4.2.7 on 2024-06-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_student_level_of_knowledge_airequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Теория темы',
                'verbose_name_plural': 'Теории темы',
            },
        ),
    ]
